# Generated by Django 4.1.7 on 2023-03-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UrbanFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contacts', models.CharField(max_length=13)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('nin', models.CharField(blank=True, max_length=14, null=True)),
                ('activities', models.ManyToManyField(blank=True, to='farmers.activity')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_no', models.CharField(max_length=100, unique=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nin', models.CharField(blank=True, max_length=14, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('pos', models.CharField(blank=True, max_length=50, null=True)),
                ('activities', models.ManyToManyField(blank=True, to='farmers.activity')),
            ],
        ),
    ]
