# Generated by Django 4.1.7 on 2023-03-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerone',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='farmerone',
            old_name='pos',
            new_name='period_of_stay',
        ),
        migrations.RenameField(
            model_name='urbanfarmer',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
