# Generated by Django 4.1.7 on 2023-03-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money')], max_length=100)),
                ('directions', models.CharField(max_length=255)),
                ('mode_of_delivery', models.CharField(max_length=255)),
                ('produce_type', models.CharField(choices=[('Organic', 'Organic'), ('Non-Organic', 'Non-Organic')], max_length=20)),
                ('available', models.BooleanField()),
            ],
        ),
    ]
